### ISSUE TITLE
Service not saving the record to the folder.

### ISSUE THREAD

**Issue by isaacmg410** [nickpourazima/rotary-phone-audio-guestbook#9]
hi @nickpourazima .
I've another error right now, when trying to run the service...

Everything is working fine, but the "record" it's not saved to the folder. And this is the error trace..
 
sudo systemctl status audioGuestBook.service
```
● audioGuestBook.service - Rotary Phone Guest Book Project
     Loaded: loaded (/etc/systemd/system/audioGuestBook.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-08-20 19:23:23 BST; 5min ago
   Main PID: 7621 (python3)
      Tasks: 6 (limit: 1595)
        CPU: 4.266s
     CGroup: /system.slice/audioGuestBook.service
             └─7621 python3 /home/isaacmassot/Desktop/rotaryGuestBook/audioGuestBook.py

Aug 20 19:23:36 raspberrypi env[7621]:     super(HoldMixin, self)._fire_activated()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 364, in _fire_activated
Aug 20 19:23:36 raspberrypi env[7621]:     self.when_activated()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/home/isaacmassot/Desktop/rotaryGuestBook/audioGuestBook.py", line 52, in off_hook
Aug 20 19:23:36 raspberrypi env[7621]:     audio_interface.stop()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/home/isaacmassot/Desktop/rotaryGuestBook/audioInterface.py", line 65, in stop
Aug 20 19:23:36 raspberrypi env[7621]:     self.stream.stop_stream()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/home/isaacmassot/.local/lib/python3.9/site-packages/pyaudio.py", line 528, in stop_stream
Aug 20 19:23:36 raspberrypi env[7621]:     pa.stop_stream(self._stream)
Aug 20 19:23:36 raspberrypi env[7621]: OSError: Stream not open
````
if I chek with journalctl -xe
```
ug 20 19:23:29 raspberrypi env[7621]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Aug 20 19:23:29 raspberrypi env[7621]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Aug 20 19:23:29 raspberrypi env[7621]: ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Aug 20 19:23:30 raspberrypi env[7621]: Cannot connect to server socket err = No such file or directory
Aug 20 19:23:30 raspberrypi env[7621]: Cannot connect to server request channel
Aug 20 19:23:30 raspberrypi env[7621]: jack server is not running or cannot be started
Aug 20 19:23:30 raspberrypi env[7621]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Aug 20 19:23:30 raspberrypi env[7621]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Aug 20 19:23:36 raspberrypi env[7621]: Traceback (most recent call last):
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 223, in _call_when_changed
Aug 20 19:23:36 raspberrypi env[7621]:     super(RPiGPIOPin, self)._call_when_changed()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/pins/local.py", line 128, in _call_when_changed
Aug 20 19:23:36 raspberrypi env[7621]:     super(LocalPiPin, self)._call_when_changed(
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 298, in _call_when_changed
Aug 20 19:23:36 raspberrypi env[7621]:     method(ticks, state)
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/input_devices.py", line 182, in _pin_changed
Aug 20 19:23:36 raspberrypi env[7621]:     self._fire_events(ticks, bool(self._state_to_value(state)))
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 401, in _fire_events
Aug 20 19:23:36 raspberrypi env[7621]:     self._fire_activated()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 447, in _fire_activated
Aug 20 19:23:36 raspberrypi env[7621]:     super(HoldMixin, self)._fire_activated()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 364, in _fire_activated
Aug 20 19:23:36 raspberrypi env[7621]:     self.when_activated()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/home/isaacmassot/Desktop/rotaryGuestBook/audioGuestBook.py", line 52, in off_hook
Aug 20 19:23:36 raspberrypi env[7621]:     audio_interface.stop()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/home/isaacmassot/Desktop/rotaryGuestBook/audioInterface.py", line 65, in stop
Aug 20 19:23:36 raspberrypi env[7621]:     self.stream.stop_stream()
Aug 20 19:23:36 raspberrypi env[7621]:   File "/home/isaacmassot/.local/lib/python3.9/site-packages/pyaudio.py", line 528, in stop_stream
Aug 20 19:23:36 raspberrypi env[7621]:     pa.stop_stream(self._stream)
Aug 20 19:23:36 raspberrypi env[7621]: OSError: Stream not open
Aug 20 19:23:42 raspberrypi sudo[7676]: isaacmassot : TTY=pts/0 ; PWD=/home/isaacmassot/Desktop/rotaryGuestBook ; USER=root ; COMMAND=/usr/bin/systemctl status audioGue>
Aug 20 19:23:42 raspberrypi sudo[7676]: pam_unix(sudo:session): session opened for user root(uid=0) by isaacmassot(uid=1000)
Aug 20 19:23:42 raspberrypi sudo[7676]: pam_unix(sudo:session): session closed for user root
Aug 20 19:27:46 raspberrypi sudo[8202]: isaacmassot : TTY=pts/0 ; PWD=/home/isaacmassot/Desktop/rotaryGuestBook ; USER=root ; COMMAND=/usr/bin/systemctl status audioGue>
Aug 20 19:27:46 raspberrypi sudo[8202]: pam_unix(sudo:session): session opened for user root(uid=0) by isaacmassot(uid=1000)
Aug 20 19:27:46 raspberrypi sudo[8202]: pam_unix(sudo:session): session closed for user root
````

Any idea on how to solved? Thanks in advance,

**Comment by nickpourazima** [comment]
Hi @isaacmg410 , apologies for the late response. We're you able to resolve this? Was it a permissions issue?
